### ISSUE TITLE
All API endpoints needed (list attached)

### ISSUE THREAD

**Issue by ejdejesu** [ejdejesu/ToxicantVisualizer#30]
here is the list off all the endpoints the API must support.

![image](https://user-images.githubusercontent.com/10540132/96652041-1a7b0980-1304-11eb-9613-f7766196e271.png)

**Comment by ejdejesu** [comment]
the api must send the response back in the form of JSON. for an example of how to do this, see the `/stats/location/facility_releases` code.

**Comment by adwait97** [comment]
'stats/state/summary' endpoint for the release-graphs isn't listed, I think we missed some

**Comment by adwait97** [comment]
![distinct err](https://user-images.githubusercontent.com/9941328/96688086-bc274880-134e-11eb-975d-5f571a0efce0.PNG)
