### ISSUE TITLE
Add About page

### ISSUE THREAD

**Issue by ejdejesu** [ejdejesu/ToxicantVisualizer#75]
meant to do this sooner

**Comment by npfah38** [comment]
Suggested text for About Page:


About

The Visualizer of Environmental Toxicants (VET) web application was developed to obtain information from the Toxic Releases Inventory (TRI) [href="https://www.epa.gov/toxics-release-inventory-tri-program"] data of the U.S. Environmental Protection Agency, and associated chemical information from the PubChem database of the National Library of Medicine [href="https://pubchem.ncbi.nlm.nih.gov"], to map, organize and visualize information about releases of toxic chemicals into the air, land and water across the U.S. 

This tool was created to expand knowledge about environmental pollutants and enable the public, scientists and policymakers to learn about patterns of releases of toxic chemicals into the air, land and water, and how these releases may be affecting communities across the U.S. 

Toxicity is a complex subject matter, and the hazards of an element are dependent on amount and concentration, among other factors. This tool is thus for exploratory purposes only, and it is not intended to diagnose any particular disease or prescribe any particular treatment. 

VET was developed for the Lab for Health and Environmental Information (LHEI) at Wayne State University by Evan de Jesus, Adwait Wadekar, Richard Moore, and Calvin Brooks as part of their Senior Capstone Project, during the Fall of 2020. The project was guided by Nic DePaula, Director of LHEI and Assistant Professor at the School of Information Sciences at Wayne State University. 

[Add a different background image to about page. Suggestions: https://unsplash.com/photos/5Yn9aQo08nc  OR https://unsplash.com/photos/6xeDIZgoPaw ]

Photo credit main page: https://unsplash.com/@punkidu
Photo credit about page:
