### ISSUE TITLE
National Insights maps turning black after filter changes

### ISSUE THREAD

**Issue by npfah38** [ejdejesu/ToxicantVisualizer#95]
When querying for Detroit, MI the "national insights" maps first produces coherent maps. 

National insights maps also seem to correctly filter for "air", "land", "water" etc...

However, after changing some filters (e.g release type, carcinogen) "national insights" maps turn black and have a strange lower-bound number: 19007199.3Bn lbs 

![image](https://user-images.githubusercontent.com/3999605/100681180-27e2d500-3341-11eb-8dd9-4b34f65bb056.png)

State map under Facilities map also seems to get screwed up...

**Comment by ejdejesu** [comment]
Rich is currently working on this (see #77 )
