### ISSUE TITLE
Change graph title as filter changes - Top tens

### ISSUE THREAD

**Issue by npfah38** [ejdejesu/ToxicantVisualizer#97]
When the user select a particular release type (e.g. "air" or "water") under "Location Insights", "Top tens", add the selected release type, year, and chemical, to the graph title as the filters may change.

Also, remove words "the" and "(in lbs)" from graph titles

Total releases in [Detroit, Mi] in [2019] - All chemicals
Total releases for 10 top facilities in [Detroit, MI] in [2019] - All chemicals
Total [Air] releases for 10 top facilities in [Detroit, MI] in [2018] - Arsenic 
Total [Water] releases for 10 top parent companies in [Detroit, MI]* in [2019]

* Make sure to add location as well, which may have been identified in a separate issue

**Comment by ejdejesu** [comment]
@npfah38 should we add literal bracket characters in the title as well, or was that just written to demonstrate the title?
